/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thirdparty_login_LoginManager */

#ifndef _Included_com_thirdparty_login_LoginManager
#define _Included_com_thirdparty_login_LoginManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_thirdparty_login_LoginManager_AccountAction_Login
#define com_thirdparty_login_LoginManager_AccountAction_Login 1L
#undef com_thirdparty_login_LoginManager_AccountAction_Logout
#define com_thirdparty_login_LoginManager_AccountAction_Logout 2L
#undef com_thirdparty_login_LoginManager_NeedThirdExitMenu
#define com_thirdparty_login_LoginManager_NeedThirdExitMenu 1L
#undef com_thirdparty_login_LoginManager_NoThirdExitMenu
#define com_thirdparty_login_LoginManager_NoThirdExitMenu 0L
/*
 * Class:     com_thirdparty_login_LoginManager
 * Method:    nativeOnActionResult
 * Signature: (IIZLcom/thirdparty/login/ThirdPartyUserInfo;)V
 */
JNIEXPORT void JNICALL Java_com_thirdparty_login_LoginManager_nativeOnActionResult
  (JNIEnv *, jclass, jint, jboolean, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
